[package]
name = "Nephrid"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "Nephrid"

[lib]
name = "nephrid"

[dependencies]
anyhow = "1.0.86"
const_for = "0.1.5"
crunchy = "0.2.2"
impl_ops = "0.1.1"
itertools = "0.13.0"
paste = "1.0.15"
rand = { version = "0.8.5", features = ["small_rng"] }
thiserror = "2.0.1"
typenum = "1.17.0"

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }

[[bench]]
name = "rook_attacks"
harness = false

[[bench]]
name = "bishop_attacks"
harness = false

[[bench]]
name = "queen_attacks"
harness = false

[[bench]]
name = "king"
harness = false

[[bench]]
name = "knight_attacks"
harness = false

[[bench]]
name = "perft"
harness = false

[[bench]]
name = "bitboard"
harness = false

[[bench]]
name = "position"
harness = false

[profile.test]
opt-level = 2

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"

[profile.bench]
inherits = "release"

[profile.profiling]
inherits = "release"
debug = true