[package]
name = "Nephrid"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
const_for = "0.1.5"
crunchy = "0.2.2"
impl_ops = "0.1.1"
itertools = "0.13.0"
paste = "1.0.15"
rand = { version = "0.8.5", features = ["small_rng"] }
thiserror = "2.0.1"
typenum = "1.17.0"

[profile.test]
opt-level = 2

[profile.dev]
opt-level = 0

[profile.bench]
opt-level = 3

[profile.release]
opt-level = 3
