name: "Tests"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # cockblocked by github lfs budget 🥀
          lfs: false

      # - name: Pull LFS objects that are required for testing
      #   run:
      #     git lfs pull --include="benchmarking/resources/*"

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Check
        run: bin/check -- -D warnings
        shell: nix develop . --command bash -e {0}

      - name: Test & Dry Run Benchmarks
        run: bin/test --verbose
        shell: nix develop . --command bash -e {0}
